Repository 42-Seoul-ft-transcendence/ft_transcendence_BE, pull requests merged in 2025-05, with the labels that each got.

#55 Chore/54 register nickname google email
  package-lock.json
  src/plugins/auth/googleAuthService.ts
Labels: chore

#57 Fix/56 no user tournament delete
  src/plugins/auth/googleAuthService.ts
  src/plugins/tournament/tournamentService.ts
Labels: feat

#66 feat: Makefile 추가 - 빌드, 설치, 서버 실행 명령어 정의
  Makefile
Labels: feat

#81 feat: match 생성 후 웹소켓 접속 안할 시 로직 구현
  src/plugins/tournament/gameService.ts
  src/plugins/tournament/tournamentService.ts
  src/types/fastify.d.ts
Labels: feat

#83 [Refactor] makefile을 도커를 통해 실행시키도록 변경
  Makefile
  src/global/exceptions/exceptionHandler.ts
  src/main.ts
  src/plugins/admin/adminService.ts
  src/plugins/auth/authService.ts
  src/plugins/auth/googleAuthService.ts
  src/plugins/auth/twoFactorAuthService.ts
  src/plugins/googleDrivePlugin.ts
  src/plugins/jwtMiddleware.ts
  src/plugins/prismaPlugin.ts
  src/plugins/tournament/gameService.ts
  src/plugins/tournament/matchService.ts
  src/plugins/tournament/tournamentService.ts
  src/plugins/user/friendService.ts
  src/plugins/user/googleDriveService.ts
  src/plugins/user/userService.ts
  src/routes/admin.ts
  src/routes/auth/auth.ts
  src/routes/auth/twoFactorAuth.ts
  src/routes/tournament/match.ts
  src/routes/tournament/tournament.ts
  src/routes/user/friend.ts
  src/routes/user/user.ts
  src/utils/encryption.ts
  src/utils/jwt.ts
Labels: refactor

#84 fix: 'all' 타겟에 docker-clean 추가
  Makefile
Labels: refactor
