Repository 42-Seoul-ft-transcendence/ft_transcendence_BE, pull requests merged in 2025-04, with the labels that each got.

#10 feat/9-user-api
  package-lock.json
  package.json
  src/global/config/index.ts
  src/global/exceptions/globalException.ts
  src/main.ts
  src/plugins/auth/twoFactorAuthService.ts
  src/plugins/jwtMiddleware.ts
  src/plugins/user/userService.ts
  src/routes/auth.ts
  src/routes/twoFactorAuth.ts
  src/routes/user.ts
  src/schemas/userSchema.ts
  src/types/fastify.d.ts
  src/utils/encryption.ts
  src/utils/twoFactorAuth.ts
Labels: feat

#12 Feat/11 friend api
  src/global/config/index.ts
  src/global/exceptions/globalException.ts
  src/main.ts
  src/plugins/admin/adminService.ts
  src/plugins/jwtMiddleware.ts
  src/plugins/swagger.ts
  src/plugins/user/friendService.ts
  src/routes/admin.ts
  src/routes/friend.ts
  src/schemas/adminSchema.ts
  src/schemas/friendSchema.ts
  src/types/fastify.d.ts
Labels: feat

#15 ci: cd.yml 수정
  src/main.ts
Labels: ci

#17 fix: api 경로 수정
  src/plugins/swagger.ts
Labels: wontfix

#22 refactor: 유저 리스트 조회 api 어드민 라우트로 리펙토링
  src/routes/admin.ts
  src/routes/user.ts
  src/schemas/adminSchema.ts
  src/schemas/userSchema.ts
Labels: refactor

#26 feat: 토너먼트 관련 구현
  src/global/exceptions/globalException.ts
  src/main.ts
  src/plugins/swagger.ts
  src/plugins/tournament/tournamentService.ts
  src/routes/tournament.ts
  src/schemas/tournamentSchema.ts
  src/types/fastify.d.ts
Labels: feat

#31 feat: 토너먼트 매칭 시스템 구현
  src/global/exceptions/globalException.ts
  src/main.ts
  src/plugins/tournament/tournamentMatchService.ts
  src/routes/tournament/tournament.ts
  src/schemas/tournament/tournamentMatchSchema.ts
  src/types/fastify.d.ts
Labels: feat

#29 refac: 친구요청시 name을 활용하도록 변경
  src/plugins/user/friendService.ts
  src/routes/friend.ts
  src/schemas/friendSchema.ts
  src/types/fastify.d.ts
Labels: feat

#34 Refactor/32 api response and db schema
  .github/workflows/cd.yml
  src/plugins/user/userService.ts
  src/routes/user.ts
  src/schemas/userSchema.ts
  src/types/fastify.d.ts
Labels: refactor

#36 Refactor/32 api response and db schema
  src/plugins/jwtMiddleware.ts
  src/plugins/user/friendService.ts
  src/plugins/user/userService.ts
  src/routes/user/user.ts
  src/schemas/user/userSchema.ts
  src/types/fastify.d.ts
  src/types/user.ts
Labels: refactor

#38 Feat/25 game
  .github/workflows/cd.yml
  src/plugins/tournament/matchService.ts
  src/types/fastify.d.ts
Labels: ci

#40 feat: Match 웹소켓 엔드포인트 구현 (v1)
  src/main.ts
  src/plugins/tournament/tournamentService.ts
  src/routes/tournament/match.ts
  src/schemas/tournament/tournamentSchema.ts
  src/types/fastify.d.ts
Labels: feat

#43 feat: CORS 플러그인 추가 및 설정
  package-lock.json
  package.json
  src/main.ts
Labels: feat

#44 feat: Match 웹소켓 엔드포인트 구현 (v2)
  package-lock.json
  src/global/db/prisma.ts
  src/global/exceptions/globalException.ts
  src/plugins/tournament/gameService.ts
  src/routes/tournament/match.ts
  src/types/game.ts
  src/utils/jwt.ts
Labels: feat
